
import { ToastContainer } from 'react-toastify'
import { LanguageProvider } from '../components/languageContext'
import LayoutDecider from '../components/LayoutDecider'
import ThemeS from '../components/ThemeS'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: '',
    description: ' Generated by Torus'
  }

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <LanguageProvider>
      <div className=' relative h-[100vh] w-[100vw]  overflow-hidden'>
        <ThemeS>
          <LayoutDecider
            mode='fluid' 
            navigationStyles='horizontal' 
          >
            <main className ="h-full w-full">{children}</main>
            <ToastContainer />
          </LayoutDecider>
        </ThemeS>
      </div>
    </LanguageProvider>
  )
}
