import './globals.css'
import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/ReactToastify.min.css'
import { GetSetupKey } from './utils/setUpKey'
import "./utils/styles.css"
import "@gravity-ui/uikit/styles/fonts.css";
import GlobalContext from './globalContext'
import ToasterClientProvider from "./components/toastClientProvider"
export const metadata: Metadata = {
  title: 'TG2' ,
  description: 'TG2 Generated by Torus'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <GlobalContext>
          <ToasterClientProvider>
            <GetSetupKey>{children}</GetSetupKey>
          </ToasterClientProvider>
        </GlobalContext>
      </body>
    </html>
  )
}