import './globals.css'
import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/ReactToastify.min.css'
import { ThemeProvider, ToasterComponent, ToasterProvider } from "@gravity-ui/uikit";
import { GetSetupKey } from './utils/setUpKey'
import "./utils/styles.css"
import "@gravity-ui/uikit/styles/fonts.css";
import GlobalContext from './globalContext'

export const metadata: Metadata = {
  title: 'TOBApp' ,
  description: 'TOBApp Generated by Torus'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body >
      <GlobalContext>
        <ToasterProvider>
          <GetSetupKey>
          <ThemeProvider theme="light">{children}<ToasterComponent /></ThemeProvider>
        </GetSetupKey>
        </ToasterProvider>
        </GlobalContext>
      </body>
    </html>
  )
}