apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: tg2-uf-generator
  namespace: tg2-uf-v11
  labels:
    app: tg2-uf-generator
spec:
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 20  # 20% traffic to Canary
      - pause: {duration: 30s}  # Wait 30 seconds
      - setWeight: 50  # 50% traffic to Canary
      - pause: {duration: 60s}  # Wait 60 seconds
      - setWeight: 100  # 100% Canary (Stable)
  selector:
    matchLabels:
      app: tg2-uf-generator
  template:
    metadata:
      labels:
        app: tg2-uf-generator
    spec:
      containers:
      - name: tg2-uf-generator-frontend-container
        image: 192.168.2.164:5000/tg2-uf-v11:docker_tag
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata:
  name: tg2-uf-generator
  namespace: tg2-uf-v11
  labels:
    app: tg2-uf-generator
spec:
  selector:
    app: tg2-uf-generator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000
      #nodePort: 30001
  type: ClusterIP
