apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tg4cgfa-uf-v1-ingress
  namespace: tg4cgfa-uf-v1
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tgadev.gsstvl.com
      secretName: tg4cgfa-uf-v1-tls
  rules:
    - host: tgadev.gsstvl.com
      http:
        paths:
          - path: /tt407/cgfa/tg4cgfa/v1
            pathType: Prefix
            backend:
              service:
                name: tg4cgfa-uf-generator
                port:
                  number: 443