
import { vgph_participant_bank } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  vgph_participant_bankEntity implements vgph_participant_bank{
    @ApiProperty({example:"bigint"})
    vgphpb_id:bigint;
    @ApiProperty({example:"string"})
    bank_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_short_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    sort_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    clearing_sort_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bic_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    iban_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    ifsc:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    country_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address_1:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address_2:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    city:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    state_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    zip_code:string;
    @ApiProperty({example:"string"})
    is_active:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    email_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    contact_no:string;
    @ApiProperty({example:"string"})
    is_small_bank:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}
      
export class  vgph_participant_bank_OnlyParentEntity {
    @ApiProperty({example:"bigint"})
    vgphpb_id:bigint;
    @ApiProperty({example:"string"})
    bank_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_short_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    sort_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    clearing_sort_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bic_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    iban_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    ifsc:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    country_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address_1:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address_2:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    city:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    state_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    zip_code:string;
    @ApiProperty({example:"string"})
    is_active:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    email_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    contact_no:string;
    @ApiProperty({example:"string"})
    is_small_bank:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}


export { vgph_participant_bank };