import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import LogoutPage from "../components/logout";
import { ThemeProvider } from "@gravity-ui/uikit";
import { Grid } from "@gravity-ui/page-constructor";
import ThemeS from '../components/ThemeS'
import { LanguageProvider } from '../components/languageContext';
import LayoutDecider from '../components/LayoutDecider';


export const metadata: Metadata = {
  title: 'TG2',
  description: 'TG2 Generated by Torus'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <LanguageProvider>
      <ThemeS>
        <div className=' relative h-[100vh] w-[100vw] '>
          <LayoutDecider 
            mode='fluid' 
            navigationStyles='vertical' 
            sidebarStyle='default'
            >
          
                <main>{children}</main>
          
              <ToastContainer />
            </LayoutDecider>
          </div>
      </ThemeS>
    </LanguageProvider>
  )
}
