
import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import LogoutPage from "../components/logout";
import { ThemeProvider } from "@gravity-ui/uikit";
import { Grid } from "@gravity-ui/page-constructor";
import ThemeS from '../components/ThemeS'
import { LanguageProvider } from '../components/languageContext';
import LayoutDecider from '../components/LayoutDecider';

export const metadata: Metadata = {
  title: 'TG4CGFA',
  description: 'TG4CGFA Generated by Torus'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <LanguageProvider>
      <ThemeS>
        <div className=''>
          <LayoutDecider 
            mode='fluid' 
            navigationStyles='vertical' 
            >
           <div>
              <main>{children}</main>    
            </div>      
              <ToastContainer />
            </LayoutDecider>
          </div>
      </ThemeS>
    </LanguageProvider>
  )
}
