pipeline {
    agent {
        label 'slave-195'
    }
    tools {
        jdk 'jdk17' 
        nodejs 'Node20.0.0'
    }
    environment {
        DOCKERHUB_USERNAME = "192.168.2.164:5000"
        APP_NAME = "ct010-a001-df-v1"
        IMAGE_NAME = "${DOCKERHUB_USERNAME}/${APP_NAME}"
        BUILD_NUMBER = "${BUILD_NUMBER}"
        GITHUB_CREDENTIALS = "GIT_HUB_PAT"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    triggers {
        githubPush() 
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Code Checkout') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${GITHUB_CREDENTIALS}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    git branch: 'master', credentialsId: "${GITHUB_CREDENTIALS}", url: 'https://github.com/TorusDev2023/Claims5UF.git'
                }
            }
        }

        stage('Detect Changes in ct010 App') {
            steps {
                script {
                    def diff = sh(script: "git diff --name-only HEAD~1 HEAD", returnStdout: true).trim()
                    if (diff.split('\n').any { it.startsWith('apps/CT010/AG001/A001/v1/Nest-df/') }) {
                        env.NEST_DF_CHANGED = "true"
                        echo "Changes detected in apps/CT010/AG001/A001/v1/Nest-df"
                    } else {
                        env.NEST_DF_CHANGED = "false"
                        echo "No changes in apps/CT010/AG001/A001/v1/Nest-df. Skipping build and deployment stages."
                    }
                }
            }
        }

        stage('Docker Buildx & Push') {
            when {
                expression { return env.NEST_DF_CHANGED == "true" }
            }
            steps {
                script {
                    docker.withRegistry("http://${DOCKERHUB_USERNAME}", '') {
                        sh """
                        export DOCKER_BUILDKIT=1
                        docker buildx use default
                        
                        docker buildx build \
                          --build-arg BUILDKIT_INLINE_CACHE=1 \
                          --tag ${IMAGE_NAME}:${IMAGE_TAG} \
                          --file apps/CT010/AG001/A001/v1/Nest-df/Dockerfile \
                          apps/CT010/AG001/A001/v1/Nest-df \
                          --push
                        """
                    }
                }
            }
        }

        stage('Update Kubernetes Deployment File') {
            when {
                expression { return env.NEST_DF_CHANGED == "true" }
            }
            steps {
                script {
                    sh "sed -i 's/docker_tag/${IMAGE_TAG}/g' apps/CT010/AG001/A001/v1/Nest-df/kubernetes/deploymentservice.yaml"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            when {
                expression { return env.NEST_DF_CHANGED == "true" }
            }
            steps {
                script {
                    withKubeConfig(credentialsId: 'kubernetes-195', serverUrl: 'https://lb.kubesphere.local:6443') {
                        sh "kubectl get ns ct010-a001-df-v1 || kubectl create ns ct010-a001-df-v1"
                        sh "kubectl apply -f apps/CT010/AG001/A001/v1/Nest-df/kubernetes/deploymentservice.yaml"
                        sh "kubectl apply -f apps/CT010/AG001/A001/v1/Nest-df/kubernetes/gateway-df-ingress.yaml"                      
                    }
                }
            }
        }

        stage('Remove Previous Build Image') {
            when {
                expression { return env.NEST_DF_CHANGED == "true" }
            }
            steps {
                script {
                    def prevBuildNumber = env.BUILD_NUMBER.toInteger() - 1
                    if (prevBuildNumber > 0) {
                        sh "docker rmi -f ${IMAGE_NAME}:${prevBuildNumber} || true"
                    }
                }
            }
        }
    }
}