apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ct010-itax-df-v1-ingress
  namespace: ct010-itax-df-v1
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"

    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tgadev.toruslowcode.com
      secretName: ct010-itax-df-v1-tls
  rules:
    - host: tgadev.toruslowcode.com
      http:
        paths:
          - path: /ct010/i001/itax/v1/api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ct010-itax-df-generator
                port:
                  number: 443