apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tg4cgfa-df-v1-ingress
  namespace: tg4cgfa-df-v1
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tgadev.gsstvl.com
      secretName: tg4cgfa-df-v1-tls
  rules:
    - host: tgadev.gsstvl.com
      http:
        paths:
          - path: /tt407/cgfa/tg4cgfa/v1/api-int(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tg4cgfa-df-generator
                port:
                  number: 443