
import { vgph_charge_tran } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  vgph_charge_tranEntity implements vgph_charge_tran{
    @ApiProperty({example:"bigint"})
    vgphct_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    charge_group:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    charge_description:string;
    @ApiProperty({example:"string"})
    currency:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vgphsm_uuid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vgphss_uuid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vgphstm_uuid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vgphsts_uuid:string;
    @ApiProperty({example:"string"})
    charge_code:string;
    @ApiProperty({example:"number"})
    charge_amount:number;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    charge_additional:any;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    charge_dr_gl_account:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    charge_cr_gl_account:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vat_flag:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    vat_amount:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vat_dr_gl_account:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vat_cr_gl_account:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    posted_flag:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    posted_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    invoice_generation_flag:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    invoice_id:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}
      
export class  vgph_charge_tran_OnlyParentEntity {
    @ApiProperty({example:"bigint"})
    vgphct_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    charge_group:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    charge_description:string;
    @ApiProperty({example:"string"})
    currency:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vgphsm_uuid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vgphss_uuid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vgphstm_uuid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vgphsts_uuid:string;
    @ApiProperty({example:"string"})
    charge_code:string;
    @ApiProperty({example:"number"})
    charge_amount:number;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    charge_additional:any;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    charge_dr_gl_account:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    charge_cr_gl_account:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vat_flag:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    vat_amount:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vat_dr_gl_account:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vat_cr_gl_account:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    posted_flag:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    posted_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    invoice_generation_flag:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    invoice_id:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}


export { vgph_charge_tran };