
import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import { LanguageProvider } from '../components/languageContext';
import LayoutDecider from '../components/LayoutDecider';
import { GlobalProvider } from '@/context/GlobalContext';
import { EventBusProvider } from '@/context/EventBusContext';
import { ThemeWrapper } from '@/components/ThemeWrapper';
import { GetSetupKey } from '../utils/setUpKey';

export const metadata: Metadata = {
  title: 'Veracious Message Convertor',
  description: 'Veracious Message Convertor Generated by Torus'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
  <GlobalProvider>
    <EventBusProvider>
      <ThemeWrapper>
      <LanguageProvider>
        <GetSetupKey>
        <div className=''>
            <div>
              <main>{children}</main>    
            </div>      
              <ToastContainer />
          </div>
        </GetSetupKey>
      </LanguageProvider>
      </ThemeWrapper>
    </EventBusProvider>
  </GlobalProvider>
  )
}
