
import { vgph_corporate } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  vgph_corporateEntity implements vgph_corporate{
    @ApiProperty({example:"bigint"})
    vgphc_id:bigint;
    @ApiProperty({example:"string"})
    vgphsc_uuid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    uuid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    charge_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    account_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    type:string;
    @Transform(({ value }) => value?.toISOString().split('T')[0])
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    inception_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    mobile_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    email:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address1:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address2:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address3:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address4:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    country:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    zip:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    state:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    city:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    reference_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    landline_no:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    is_active:string;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    product_basic:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    product_additional:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    contacts:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    request_data:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    response_data:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    compliance_data:any;
    @Transform(({ value }) => value?.toISOString())
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}
      
export class  vgph_corporate_OnlyParentEntity {
    @ApiProperty({example:"bigint"})
    vgphc_id:bigint;
    @ApiProperty({example:"string"})
    vgphsc_uuid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    uuid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    charge_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    account_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    type:string;
    @Transform(({ value }) => value?.toISOString().split('T')[0])
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    inception_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    mobile_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    email:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address1:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address2:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address3:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address4:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    country:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    zip:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    state:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    city:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    reference_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    landline_no:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    is_active:string;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    product_basic:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    product_additional:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    contacts:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    request_data:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    response_data:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    compliance_data:any;
    @Transform(({ value }) => value?.toISOString())
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}


export { vgph_corporate };